[package]
name = "r0-prover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gevulot-shim = { git = "https://github.com/gevulotnetwork/gevulot.git" }
